import { useEffect } from 'react'
import Container from '../components/ui/Container'
import Heading from '../components/ui/Heading'

const TermsAndConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  return (
    <section className="bg-[#070210]">
      <Container>
        <div className='w-full mx-auto max-w-screen-2xl'>
          <Heading title="Terms And Conditions" />
          <div className='text-white text-left my-8 space-y-5'>
            <p className="">These are the Company Terms and Conditions of Use (‘Terms’) which form a legal and binding agreement amongst Eirupskills infotech llp (referred to as the ‘Company’, ‘Ludo Vijayta, ‘Us’, ‘We’ or ‘Our’) and any person (‘You’/ ‘Your’/ ‘User’) accessing:</p>
            <div className='space-y-6 text-left'>
              <div>
                <ol className='pl-8 list-decimal w-full space-y-4'>
                  <li> Our website – www.ludovijayta.com (‘Website’) and the Ludo Vijayta mobile application (‘App’) including any sub-domains of the Website, or related top-level domains including www.ludovijayta.com, mobile sites, apps, APIs, widgets (hereinafter collectively referred as ‘the Platform’), and/or;</li>
                  <li>any data, information, text, graphics, video, sound, pictures, and any other materials appearing, sent, uploaded, communicated, transmitted, or otherwise made available via the Platform (jointly referred to as the ‘Content’) for participating in various contests and games hosted on the Platform (‘ Services‘ / ‘Games’). </li>
                  <li>Such User (as described above) shall be bound by these Terms, Privacy Policy (https://ludovijayta.com/privacy-policy/), and all other rules, regulations, and terms of use (including Privacy Policy) referred to herein or provided by Company in relation to any Services of the Company.</li>
                  <li>This document is an electronic record in terms of the Information Technology Act, 2000, and rules there under as applicable and various other statutes. This electronic record is generated by a computer system and does not require any physical or digital signatures.</li>
                  <li> You acknowledge and agree that by using, or otherwise accessing the Company Platform and Company Services, you agree to be bound by these Terms and our Privacy Policy (https://ludovijayta.com/privacy-policy/). You acknowledge that we provide use and access to our Platform and Services to you, subject to these Terms. You agree and acknowledge that you have completely read and understood these Terms and the Privacy Policy, incorporated herein by reference, as amended from time to time. You agree, covenant, and undertake to be bound by the specific rules and regulations of each of the Games as applicable.</li>
                  <li> We reserve the right to amend, modify, update, terminate, supplement, or otherwise amend all or any of the Terms, Privacy Policy, rules, or regulations on the Platform at any time by publishing new Terms. Company may, at its sole discretion, also notify the User of any change or modification in these Terms, Privacy Policy, rules, regulations, and terms of use referred to herein or provided by Company, by way of sending an email to the User’s registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms, rules, regulations, and terms of use referred to herein or provided by the Company. If such options to indicate non-acceptance are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms, rules, regulations, and terms of use referred to herein or provided by the Company.</li>
                  <li> If the User does not accept the modified Terms, rules, regulations, and terms of use referred to herein or provided by the Company, we reserve the right to deny access to the Platform and Services to the User. If the User does not accept the modified Privacy Policy, we reserve the right to deny access to the Platform and Services to the User to the extent such modified terms of the Privacy Policy are required to provide access to the Platform and Services.</li>
                  <li> Participation in any Games or contest on the Platform of the Company or viewing of certain Content may be subject to further terms and conditions as may be notified by us from time to time on the Website or otherwise. You should ensure that you have read, understood, and agree to abide by the rules and regulations of the Games, contests, and tournaments available through the Company Platform.</li>
                  <li> Company may, at its sole and absolute discretion:</li>
                  <ol className='pl-8 list-decimal w-full space-y-2'>
                    <li>Move or remove any Content that is available or posted by a User on the Platform.</li>
                    <li>Establish general practices and limits concerning the use of the Platform and modify these practices, limits, and thresholds at its discretion, from time to time, and such changes shall be notified and/or included within updated Terms as deemed fit by Company.</li>
                    <li>Assign its rights and liabilities to all User accounts hereunder to any entity (post such assignment, intimation of such assignment shall be sent to all Users to their registered email addresses).</li>
                    <li>Your use of information on our Platform including results, fixture lists, statistics, data, and news posted on our Platform is at your own risk. Other than as expressly set out in these Terms and to the extent permitted by law, we make no warranty as to the accuracy or reliability of the information contained on our Platform or in our publications (including, but not limited to, any Content or information generated on our Platform by or on behalf of us, and any third-party content on our Platform). We and our related entities, directors, officers, and agents disclaim all liability and responsibility for any loss or damage (whether direct or indirect) that may be suffered by any recipient through relying on anything contained in, or omitted from our Platform or publications.</li>
                    <li>You hereby unconditionally and irrevocably, expressly agree to the transfer of your personal data and information (including sensitive data) to Us and to such third parties who we contract with to provide you with the Services.</li>
                  </ol>
                </ol>
              </div>
              <div className="space-y-3">
                <h4 className="font-bold">Description of Services Offered</h4>
                <ol className='pl-8 list-decimal w-full space-y-4'>
                  <li>Subject to the User’s compliance with these Terms, the Company gives Users a personal, royalty-free, non-assignable, non-sublicensable, non-transferable, non-exclusive, and revocable limited right to access and use the Platform that is provided as part of the Services. This right is for the sole purpose of enabling the own personal private use from Users to play Games of skill as hosted on the Platform, in the manner prescribed under these Terms and not for any commercial purposes, in India and only until the User is bound by these Terms.</li>
                  <li>The Services may change or be modified from time to time without prior notice or communication. Company reserves the right to change, modify or delete the Platform or Services, information, and Terms listed thereon at any time without prior notice.</li>
                  <li>The Services may include advertisements, which may be targeted to the Content or information on the Services, queries made through the Services, or any other information. The types and extent of advertising by the Company on the Services are subject to change.</li>
                  <li>When Games are included in the Services, the specific rules, scoring, controls, and guidelines for each game can be found within the game itself. The Users agree to and shall comply with such rules, scoring, controls, guidelines, etc.</li>
                  <li>Any charges levied on Users for accessing the Services, including but not limited to internet connection and/or mobile or data charges are solely the responsibility of such Users.</li>
                </ol>
              </div>
              <div className="space-y-3">
                <h4 className="font-bold">User Registration</h4>
                <p className=''>In order to access the Website or fully utilize the Platform offered by the Company, a User is required to register on the Platform. You are not authorized to access any of our Platforms until you have been granted an Account (defined below).</p>
                <ol className='pl-8 list-decimal w-full space-y-4'>
                  <li>If you wish to become a registered User, you will need to create an account (‘Account’) on our Platform. Each User is only permitted to open one Account. The Company reserves the right to terminate or suspend any duplicate accounts.</li>
                  <li>In order to apply for an Account, the Company may require you to register by completing a form and providing certain details (listed below), in accordance with the instructions on the Platform:</li>
                  <ol className='pl-8 list-decimal w-full space-y-2'>
                    <li>Full Name</li>
                    <li>E-mail address</li>
                    <li>Password</li>
                    <li>State of Residence</li>
                    <li>Gender</li>
                    <li>Date of Birth</li>
                    <li>Mobile Number</li>
                    <li>Bank Account Number</li>
                    <li>Permanent Account Number Card (PAN Card)</li>
                    <li>Government-issued Identity Documents (for know-your-customer checks)</li>
                  </ol>
                  <li>You can register or log in through your Google address. You may also be required to provide your mobile number for verification purposes and verify such mobile number using a one-time passcode (OTP) sent to your mobile number. Permission to open the Account shall be determined by Company or its representatives, at their sole discretion. We may refuse to grant an application for an Account made by any person without giving a reason for such refusal. You agree and acknowledge that the decision of the Company in this regard shall be final. We may require additional identity verification procedures used to ensure that we can verify the identity of Users transacting with each other and assist our payment service providers corroborate the results of these know-your-customer verification checks with the identity of our customers (collectively ‘KYC’ checks). You understand and submit to such KYC checks, and agree and consent to supply and provide your personal information and documents to evidence proof of identity and address, as may be required to conduct and complete such KYC checks.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Eligibilty</h4>
                <p className='text-left'>You must be over 18  years of age and a resident of India to access and/or use our Platform and create an Account with us. By agreeing to these Terms, you represent and warrant to us that:</p>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>you are at least 18 years old;</li>
                  <li>you have not previously been suspended or blocked from using the Platform; and</li>
                  <li>your registration and your use of the Platform are in compliance with any and all applicable laws and regulations. You must not be a resident of any Restricted Territories (as hereinafter defined) to participate in any Games on the Platform.</li>
                  <li>We reserve the right to request proof of identity at any stage to verify that minors are not using the Platform and we may exclude a person from accessing or using the Platform if proof of identity is not provided or if the Company suspects that a person is under the age of 18 years. Parents and guardians should monitor their children’s / ward’s online activities and consider using parental control tools available from online services that help provide a child with an amicable online environment. These tools can also prevent children from disclosing any personal information without parental permission.</li>
                  <li>Employees and directors of the Company are not eligible to participate in any Games on the Platform.</li>
                  <li>You agree to provide true, accurate, current, and complete information at the time of registration and at all other times (as required by the Company).</li>
                  <li>You agree to update and keep updated all information provided for the purposes of registration.</li>
                  <li>You undertake and agree that all information provided by you from time to time is true, accurate, current, and complete to your personal knowledge.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Creation of Account and Use of the Platform</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>Upon grant of the Account by us, your Account will be created, and you will be able to use our Platform, access the Service(s), and play the Game(s) hosted by us. You agree and acknowledge that such Account can be terminated by us by giving notice to you, for any reason deemed fit by Company in its sole discretion.</li>
                  <li>You represent and warrant to us that, throughout the course of your usage of our Platform, you will not permit other persons to access or use your Account. If you permit other persons to access or use your Account, you do so at your own sole risk as to any consequences. You further agree and accept that you shall not access or use the Platform through the Account of another User.</li>
                  <li>Users are prohibited from operating multiple accounts. If it comes to the knowledge of the Company that a User is operating multiple accounts, in such case, Company reserves the right to restrict, ban, suspend, or terminate such User’s Accounts, at its sole and absolute discretion and without any notice. Any cash or credit balances in such User’s Accounts are liable to be consolidated into the Account with the highest cash or credit balances or forfeited at the sole discretion of the Company, depending on whether such Accounts are aliases or Accounts associated with actual or potential frauds.</li>
                  <li>You may also be required to verify any credit card/bank account you use to deposit funds, and also any bank account you want to withdraw to ensure their integrity and verify their compliance with current regulations.</li>
                  <li>In the event You are erroneously credited excess funds for any reason, You forfeit the excess amount, and such amount shall be debited from Your Account.</li>
                  <li>Where Company conducts any customer identity checks, this neither implies that Company is statutorily required to conduct such checks nor liable for any inaccuracy in customer verification that cannot be directly attributable to Company’s gross negligence. You are responsible for completing your ‘know your customer’ checks with your respective banks, financial institutions, card associations, and other payment system providers as defined under the Payment and Settlement Systems Act, 2007 (Payment System Providers), with whom the Company has entered into an arrangement to facilitate payment transactions (i.e. to send or receive funds via the Platform) using the services of such Payment System Providers. The Company conducts such checks as a measure to reduce financial crime in its multiple forms, such as online fraud, money laundering, or the financing of terrorism.</li>
                  <li>By accepting these terms and conditions upon registration, you give consent to Company to disclose your personal information provided to us to a third-party agency to assist in verifying your identity. The third-party agency may prepare and provide Company with such an assessment and may use your personal information including names, residential addresses and dates of birth, financial information, etc. for the purposes of preparing such an assessment. Please refer to our Privacy Policy in this regard.</li>
                  <li>You acknowledge that your participation in any Game(s) available on the Platform is purely voluntary and at your sole discretion and risk.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Skill Based Quiz games played on the Platform do not qualify as Gambling and Lottery</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>Only games of skill are hosted on the Platform. Each game shall be governed by the skill set, performance, and effort you demonstrate to play and achieve the outcome.</li>
                  <li>Users acknowledge that the Games hosted on the Platform are games of skill under Indian law and that we do not support, endorse, or offer to Users any game of chance. While games of skill do not have a comprehensive definition, they are considered to be those games where the impact of a player’s effort and skill on the outcome of a game is higher than the impact of luck on the outcome of a game.</li>
                  <li>Games hosted on the Platform are games of skill, as the outcome/success of the game is directly dependent on the Users’ effort, performance, and skill. The Supreme Court of India has recognized that the right to play games of skill is a constitutionally protected right.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Restricted Territories </h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>The Platform is not offered in Andhra Pradesh, Arunachal Pradesh, Assam, Meghalaya, Nagaland, Odisha, Telangana, Sikkim, Tamil Nadu, and outside India</li>
                  <li>Company may, in accordance with the laws prevailing bar individuals residing in the Indian states of Andhra Pradesh, Arunachal Pradesh, Assam, Meghalaya, Nagaland, Odisha, Telangana, Sikkim, Tamil Nadu, and outside India, not allowed to participate in the paid versions of the Game(s) as the laws of these states bar persons from participating in games of skill where Users are required to pay to enter. Access to the Platform will therefore be restricted from being accessed by Users from such states. Please note that free-to-play versions of our Game(s) can be accessed in the aforesaid territories.</li>
                  <li>The Company does not allow the Users residing in the aforesaid Indian states or outside the territory of India to play with real money or deposit amounts to play Games on the Platform. We verify the User(s) location by utilizing certain technologies for monitoring of activities including logging of IP address and your geographical location and User(s) hereby consents for collection of aforementioned information. The Company reserves the right to delete/remove such Account(s) without any notice and in its sole and absolute discretion.</li>
                  <li>Users agree and acknowledge that if a person residing in such an Indian state becomes a User by giving false information, the liability shall be solely on the User, and Company reserves the right to delete/remove such Account without any notice and such User shall not have any right to redeem or demand the Account balance of such Account.</li>
                  <li>You agree and accept that the Company shall not be liable or responsible for the breach of applicable state laws by any User. There may be applicable penalties imposed on such Users by the respective State Governments or the Central Government of India as the case may be.</li>
                  <li>Users from all Indian states have to always ensure that they are complying with the applicable state laws, and we will attempt to post any changes that we deem appropriate to better educate the Users. You agree and acknowledge that our decision in this regard will be final and binding, and no consideration whatsoever will be extended to the User.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Payment Terms </h4>
                <p className=''>In respect of any transactions entered into on the Platform for playing Games and contest(s), Users agree to be bound by the following payment terms to which Users shall be bound when participating in any game and the User will pay the contribution (Contribution) which will be inclusive of the following:</p>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>Pre-designated Platform fee (Platform Fee) (for each kind of game hosted by the Company, as described within the Games) for access to the Platform. Such Platform Fee is inclusive of applicable GST; and Pre-determined Contribution towards the prize money pool (Prize Money Pool) of such game/contest as stipulated by the Company, which will be passed on to the winner(s) of the game/contest after the completion of the game/contest as per the terms and conditions thereto. Company reserves the right to deny its Platform/ Services to any User at its sole and absolute discretion. Such denial would automatically disqualify a User from playing any Games hosted on the Platform.</li>
                  <li>Unless specifically identified in these terms, it is clarified that Company has no right or interest in this Prize Money Pool, and only acts as an intermediary engaged in collecting and distributing the Prize Money Pool in accordance with the game terms and conditions.</li>
                </ol>
                <p className='text-left text-white'> In respect of any transactions entered into on the Platform, including making a payment to participate in the Games, the Users agree to be bound by the following payment terms:</p>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>Subject to these Terms, all amounts collected from the User are held in separate non-interest earning bank accounts of the Company.</li>
                  <li>From these bank accounts, the payouts can be made to, Users(towards their withdrawals of Winnings subject to applicable taxes), while the Company retains the amount towards its Platform Fees. The Company shall receive and hold the amounts of the Users in trust as a trustee of and for the benefit and use of the Users.</li>
                  <li>The Company receives only its share of the Platform Fees and the User funds are held merely as a trustee for the benefit and use of the Users.</li>
                  <li>The Company reserves the right to charge a Platform Fee, which would be specified and notified by it, prior to a User’s joining a game. The Platform Fee (inclusive of applicable tax thereon) will be debited from the User’s Account balance and the Company shall issue an invoice for such debit to the User. The Platform fee (inclusive of applicable tax thereon) will be debited from the Users Account balance and Company shall issue an invoice for such debit of the User. The Platform Fee may be dynamic on a game-to-game basis and dependent on factors such as the number of Users, eligibility criteria, ranking, server load, etc., subject to the Platform Fee being determined before the commencement of a game.</li>
                  <li>The User may participate in a game wherein the User has to contribute a pre-specified Contribution towards the Prize Money Pool of such game, which will be passed on to the winner(s) of the game after the completion of the game as per the terms and conditions of such game.</li>
                  <li>Any User availing of Services is provided with the following categories of amounts for the processing and reconciliation of payments</li>
                </ol>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>Play Money - comprises money contributed/deposited by the User through a payment gateway in its wallet (Play Money). Play Money once deposited cannot be withdrawn and can only be utilized to play/participate in a Game or contest.</li>
                  <li>Prize Money - comprises of the money including in kind, won by the Users by winning the game/contest(s) (Winnings). Winnings can be withdrawn after an applicable tax deduction, if applicable.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Referral Bonus / Rewards </h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>The Company may offer referral programs (Referral Program) on the Platform to allow all its Users to receive certain rewards in the form of cash Bonus (Rewards) for each player that they refer to play on the Platform;</li>
                  <li>All active Users of the Platform are eligible to participate in the Referral Program except in cases where an Account has been suspended.</li>
                  <li>Only ‘successful referrals’ will be counted and eligible to receive the Rewards. A successful referral is an event in which a new User will register on the Platform and complete the sign-up by clicking on the referral link of the referrer or by putting the referrer’s unique referral code and the User will get % of the contest entry fees joined by the referee user if he wins the contest.</li>
                  <li>Criteria to use the Rewards – The User will be able to use only a certain percentage of the cumulative Rewards (as permitted by the Company from time to time) reflected in his/her Account to join any of the upcoming tournaments on the Platform.</li>
                  <li>The nature and value of Rewards to be credited will be based on the Referral Program offered by the Company at any given point in time to an individual User. Referral links will be generated from each User’s Account on the Platform. Rewards and their types are subject to change at the Company’s sole discretion without notice. Users found to have been committing fraud will be blocked from the Platform. The reward amount/type is based on the applicable reward on the day a user’s referral signs up on the Platform. We reserve the right to change rules and regulations without notice.</li>
                  <li>Users will not receive credit for referring themselves by creating multiple Accounts. The Company reserves the right, in its sole discretion, to suspend or disqualify an Account from the Referral Program or nullify the Referral Rewards.</li>
                  <li>[Invoicing and taxability of Referral Bonus]</li>
                  <ol className='list-decimal pl-8 space-y-3'>
                    <li>In case there is any amount remaining to be paid by the User in relation to such User’s participation in any game(s), the User will be taken to the designated payment gateway to give effect to such payment. In case any amount added by the User through such payment gateway exceeds the remaining amount of the Contribution, the amount in excess shall be transferred to the Account and will be available for use in participation in the game(s).</li>
                    <li>Notwithstanding any other provisions, in cases where the Winnings are double credited to the Users Account, the User hereby undertakes, agrees, and authorizes the Company to have the right to reclaim, impose lien and freeze the account of the User until the amount is re-claimed by the Company.</li>
                    <li>In order to request a withdrawal of any amount standing in the Play Money, the User must first complete Company’s identity verification, and bank account verification, which will also require submission of the User’s PAN card and bank account details and providing a reason for withdrawal over email. Company shall effect an online transfer to the User’s bank account on record with Company, within a commercially reasonable period of time. Such transfer will reflect as a debit to the User’s Play Money. The Company may, in certain exceptional circumstances and at its sole and absolute discretion, refund the amount to the User after deducting applicable cancellation charges and taxes including GST.</li>
                    <li>Further, withdrawal of any amount standing to the User’s credit in the Winnings may be made by way of a request to the Company. In such case, the Company shall cause an online transfer to the User’s bank account on record with the Company by instructing, within a commercially reasonable period of time. Such transfer will reflect as a debit to the User’s Winnings. Company may charge any processing fee for causing the online transfer of such amount from the Winnings to the User’s bank account on record with the Company.</li>
                  </ol>
                  <li>Users may be required to complete the verification process in order to raise the withdrawal request. As a general practice, winners will be required to verify their e-mail address & phone number along with the following documents:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>a self-attested photocopy of the User’s PAN card or PAN authentication and</li>
                      <li>bank account details and proof of the User.</li>
                    </ol>
                  </li>
                  <li>Company shall not process the withdrawal of a User’s prize(s)/accumulated Winnings unless the above-mentioned documents have been received, verified, and authenticated (where applicable) within the time- period stipulated by the Company. Only to those winners who successfully complete the verification process and provide the required documents within the time limit specified by the Company shall the Company process the withdrawal of their accumulated Winnings (or any part thereof).</li>
                  <li>Company shall scrutinize all documents submitted and may, at its sole and absolute discretion, disqualify any winner from withdrawing his accumulated Winnings (or any part thereof) on the following grounds:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>Determination by the Company that any document or information submitted by the User is incorrect, misleading, false, fabricated, incomplete, or illegible; or User does not fulfill the eligibility criteria; or any other ground as reasonably determined by the Company.</li>
                      <li>The User represents and warrants that the documents provided in the course of the verification process are true copies of the original documents to which they relate.</li>
                      <li>Users are required to provide proper and complete details at the time of registration. Company shall not be responsible for communications errors, commissions, or omissions including those of the Users due to which the results may not be communicated to the Winner.</li>
                      <li>Where any of the fixtures within a game are canceled or abandoned without an official result, all game entries are considered void, and the Contribution shall be duly refunded to the User. There are no prize/Winnings pay-outs and Platform fee charges for these voided Games.</li>
                    </ol>
                  </li>
                  <li>If, in a transaction performed by you on the Platform, money has been charged to your card or bank account and the respective amount is not added to your Account within 24 hours of the completion of the transaction, then you shall inform us by sending an e-mail to care@Sikandarji.in  from your registered e-mail address. Please include the following details in the e-mail (1) your mobile number, (2) transaction value, (3) transaction date, and (4) transaction ID. The Company will investigate the incident and, if it is found that money was indeed charged to your card or bank account without delivery of the balance in your Account, then you will be refunded the money within 7 business days from the date of receipt of your e-mail. All refunds will be credited to your Account.</li>
                  <li>The Company may withdraw and/or cancel any contest(s) to be conducted or already conducted, without prior notice to any Users or winners of any Game(s)/Contest(s). In such an event, the Company shall effect a refund of the amount of Contribution money contributed by each participant.</li>
                  <li>Applicability of tax deducted at source (‘TDS’) w.e.f April 01, 2023: As per the relevant provisions of the Income Tax Act, 1961 (‘Act’) read with rules and regulations thereunder, TDS is required to be deducted at the applicable rates in force on the “net winnings”, whether in cash or in kind or partly in cash or partly in kind, of a user.
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>Event of deductibility of taxes: TDS is required to be deducted from the Net Winnings at the time of every withdrawal from the User account and/or balance in the User account at the end of the financial year, from ‘net winnings’ comprised in the withdrawn amount and/ or balance at end of the financial year, as the case may be.</li>
                      <li>Rate of TDS: TDS is required to be deducted at the rate of 30% (thirty percent) as prescribed by the Government of India under the Act or as prescribed under applicable laws, from time to time.</li>
                      <li>User account: All the accounts/ wallets, by whatever name called, opened or maintained or operated by the User on the Platform.</li>
                      <li>Withdrawal: Any amount withdrawn from a User Account maintained with Us to the User’s bank account or any other accounts that belong to the User as may be used for any purpose other than online gaming. Any prize distributed in kind to the user will also be treated as an instance of withdrawal for the purposes of applicability and calculation of TDS.</li>
                      <li>Dissemination of TDS certificates: The User (subject to the availability of a valid PAN with the Company) shall be provided with the TDS certificate (Form 16A) in accordance with the applicable provisions.</li>
                      <li>Changes proposed in law (if any): Aforementioned TDS-related covenants are based on the understanding of the recently introduced provisions of the law. The Company reserves its rights to modify/ change/ amend the TDS covenants in case of change in TDS provisions under Applicable law and apply TDS provisions applicable at the relevant time.</li>
                      <li>Applicability of any other taxes: The User shall be responsible for bearing any other taxes as per applicable laws as amended from time to time (in addition to what is specified above). We reserve the right to deduct taxes as per the applicable provision of the Act, on any amounts that become due, payable, or paid to you. In case we believe that any such withholding tax is applicable, you agree that we can deduct and deposit the tax with the government treasury as per the stipulated timelines and debit the amount from your winnings.</li>
                    </ol>
                  </li>
                  <li>You represent and warrant to Us that You are not in the business or profession of gaming or playing games, and that any benefit/ perquisite received by You in the form of discount, bonus money, cashback, etc from Us is not arising from any business or exercising of a profession by You, for the purposes of section 194R of the (Indian) Income-tax Act, 1961</li>
                  <li>The decision of the Company with respect to the awarding of prizes shall be final, binding, and non-contestable.</li>
                  <li>To the extent permitted by law, Company makes no representations or warranties as to the quality, suitability, or merchantability of any prizes and shall not be liable in respect of the same.</li>
                  <li>The winners shall bear all transaction charges levied for the delivery of cash prizes.</li>
                  <li>All prizes are non-transferable.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Security</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>Access to your Account and to add, delete or modify any Content on your Account is password / OTP protected.</li>
                  <li>We are not liable for any loss, damages, or expenses of any kind incurred or suffered by you arising from or in connection with any failure, delay or interruption, interception, or interference, in transmitting passwords/OTPs due to any failure of the mobile service network or any other circumstance beyond our reasonable control.</li>
                  <li>You agree that you will not disclose your password / OTP to anyone or allow any other person to access or use your Account. We are not responsible if your Account is accessed or opened by other persons using your password. You shall be held solely responsible and liable for all of your activities on the Platform made from your Account.</li>
                  <li>You understand that it is your obligation to protect the information you have provided on the Platform including, but not limited to usernames, passwords, email addresses, contact details, bank account information, etc. You explicitly understand and agree that we will not incur any liability for information provided by you to anyone which may result in your Account on the Platform being exposed or misused by any other person or any other harm or loss being suffered by you.</li>
                  <li>Company shall not be liable to a User for any authorized transaction which has been executed through the Platform as a result of:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>fraud committed by any User using User’s access credentials before the User has notified Company in writing of the loss or theft of such access credentials, as a result of which Company has been unable to take any action to disable the access credentials;</li>
                      <li>fraud committed by third parties against Users which may not be preventable by, or occur despite the security systems of the Platform;</li>
                      <li>a voluntary action or transaction initiated suo motu by any User at the behest of another User, which is not initiated by the Company for the transfer of funds, credit, or stored value to another User;</li>
                      <li>the security, accuracy, legality, appropriateness, or any other aspect of the Content or function of any third party’s products or services on our Platform;</li>
                      <li>responsibility for the underlying transactions involving funds between you and the sender/recipient of a payment or the actions or identity of any transfer recipient or sender.</li>
                    </ol>
                  </li>
                  <li>You should routinely check the Account Balance section of your Account to ensure that there has been no unauthorized use of your Account. If you suspect any unauthorized activity you must change your password immediately and contact the Grievance Redressal Officer at [Insert Email id of Grievance Redressal Officer].</li>
                  <li>Please note that we can terminate or suspend your Account and all associated accounts, and institute fraud prevention measures such as access restrictions, transaction velocity restrictions, etc., without prior notice to prevent unauthorized use of our Platform. You must cooperate with us in any investigation and use any fraud prevention measures we prescribe, and you agree that we will not be liable to you or any third party for any block, suspension, cancellation, or termination of your use of an Account owing to such measures.</li>
                  <li>You are hereby informed that any and all information associated with any fraudulent transaction may be shared by Company (with or without demand) with the Government of India or any agency thereof, for the purpose of verification of the identity of the User, or for the prevention, detection, investigation, prosecution, and punishment.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">User Conduct</h4>
                <p>It is your sole responsibility to play Sikandarji Games for entertainment, to the extent that you comfortably can. We also offer the option of playing free games to Users. We are committed to the safety & well-being of our players, and strongly advise you to keep track of the time and money you are investing in the skill games. Please consider Sikandarji games only as a form of entertainment.</p>
                <p>In accessing or using our Platform you agree that you will not:</p>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>use any automated device, software, process, or means to access, retrieve, scrape, or index our Platform or any Content thereon without our express prior written consent;</li>
                  <li>use any device, software, process, or means to interfere or attempt to interfere with the proper working of our Platform;</li>
                  <li>undertake any action that will impose a burden or make excessive traffic demands on our infrastructure that we deem, in our sole discretion, to be unreasonable or disproportionate site usage;</li>
                  <li>use or index any Content or data on our Platform for purposes of competing with us in any manner that we have not specifically authorized; transmit spam, chain letters, games, junk email, surveys, or other mass messaging, whether commercial in nature or not;</li>
                  <li>use our Platform or any Content therefrom in any manner which is, in our sole discretion, not reasonable and/or not for the purpose it is made available;</li>
                  <li>violate the rights of any person, including copyright, trade secret, privacy right, or any other intellectual property or proprietary right;</li>
                  <li>pose as any person or entity or attempt to solicit money, passwords, or personal information from any person;</li>
                  <li>act in violation of any Terms of using our Platform;</li>
                  <li>reproduce, republish, retransmit, modify, adapt, distribute, translate, create derivative works or adaptations of, publicly display, sell, trade, or in any way exploit our Platform or any Content thereon, except as expressly authorized by us; or</li>
                  <li>transmit or attempt to transmit any computer viruses, worms, defects, Trojan horses, or other items of a destructive nature.</li>
                  <li>If you choose to submit any content by way of question on the Platform, you hereby warrant that no Contribution (defined hereinafter) shall
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>be considered to be, unlawful, threatening, abusive, bigoted, hateful, libelous, tortious, blasphemous, false or misleading, discriminatory, defamatory, obscene, vulgar, offensive, excessively violent, invasive of another’s privacy, publicity, contract, or other rights, pornographic or inclusive of nudity, pedophilic, profane, sexually explicit, indecent, racially, ethnically objectionable, disparaging, relating or encouraging money laundering, or otherwise unlawful in any manner whatsoever</li>
                      <li>constitute, advocate, or encourage conduct that would constitute or give rise to a criminal offense, civil liability, or other violation of any local, state, national, or international law;</li>
                      <li>constitute or contains false or misleading indications of origin or statements of fact;</li>
                      <li>belongs to another person and to which you do not have any right to, or infringe the intellectual property rights (whether registered or unregistered) of the Company or any third party;</li>
                      <li>contain any information, software, or other material of a commercial nature or is patently false or untrue;</li>
                      <li>contain advertising, promotions, or commercial solicitations of any kind;</li>
                      <li>harass or harm another person;</li>
                      <li>exploit or endanger a minor;</li>
                      <li>impersonate or attempt to impersonate any person or entity or mislead or attempt to mislead another person regarding your identity;</li>
                      <li>threaten the unity, integrity, defense, security, or sovereignty of the territory, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offense or prevents investigation of any offense or is insulting any other nation.</li>
                      <li>As it concerns the content uploaded by you, without prejudice to your obligation to otherwise comply with applicable laws during the course of using the Platform, you agree to hereby comply with any and all applicable laws, as well as any other rules and restrictions that may be set forth herein or on the Platform. The Company may not be held responsible for any content posted, or contributed by Users on the Platform.</li>
                      <li>The Users admit that they may be exposed to Content posted by other Users which they may find offensive, obnoxious, or indecent and that we may not be able to prevent such Content from being posted. Such Content should be brought to our notice. We shall act upon the information as it deems acceptable. The decision taken by the management of the Company in this regard shall be final and binding on the User and you specifically agree that we shall not incur any liability under any circumstance whatsoever regarding the same.</li>
                      <li>We reserve the right to prevent unauthorized access to or use of our Platform, including, but not limited to, instituting technological barriers, or reporting your conduct to any person or entity.</li>
                      <li>In the event, we have reasonable grounds to believe that your activities include any of the acts specified above, we may initiate appropriate legal action against you as well as notify the relevant regulatory or law enforcement authorities where appropriate in addition to any other available remedies under law or equity, apart from restricting or suspending or terminating your use of the Platform.</li>
                    </ol>
                  </li>
                  <li>You shall not purchase, sell, assign, trade, rent, loan, lease, license, grant a security interest in, or transfer your User Account, any content, currency, points, standings, rankings, ratings, or any other attributes appearing in, originating from or associated with the Platform.</li>
                  <li>Users agree to abide by these Terms and all other rules, regulations, and terms of use of the Platform. In the event User does not abide by these Terms and all other rules, regulations, and terms of use, Company may, at its sole and absolute discretion, take necessary remedial action, including but not limited to:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>restricting, suspending, or terminating any User’s access to all or any part of Services;</li>
                      <li>deactivating or deleting a User’s Account and all related information and files on the Account. Any amount remaining unused in the User’s game Account or winnings account on the date of deactivation or deletion shall be transferred to the User’s bank account on record with the Company subject to a processing fee (if any) applicable on such transfers as set out herein; or</li>
                      <li>refraining from awarding any prize(s) or withholding access to such infringing User.</li>
                    </ol>
                  </li>
                  <li>Users agree to ensure that they can receive all communication from the Company by marking e-mails or sending SMSs from the Company as part of their safe sender’s list. Company shall not be held liable if any e-mail/SMS remains unread by a User as a result of such e-mail getting delivered to the User’s junk or spam folder.</li>
                  <li>If a User chooses a username that, in Company’s considered opinion is obscene, indecent, abusive or that might subject Company to public disparagement or scorn, Company reserves the right, without prior notice to the User, to change the User’s username and inform the User, or delete such username and posts from Platform, deny such User access to Platform, or any combination of these options.</li>
                  <li>Unauthorized access to Platform is a breach of these Terms and a violation of the law. Users agree not to access the Platform by any means other than through the interface that is provided by Company for use in accessing Platform. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our sites, except those automated means that we have approved in advance and in writing.</li>
                  <li>The use of the Platform is subject to existing laws and legal processes. Nothing contained in these Terms shall limit the Company’s right to comply with governmental, court, and law-enforcement requests or requirements relating to the User’s use of the Platform.</li>
                  <li>The Company may not be held responsible for any content contributed by Users on the Platform.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Prevention of Collusion and Fraud</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>We are committed to promoting fair play on our Platform.</li>
                  <li>Our compliance team will track the gameplay of all Users and strict action will be taken against any User(s) caught colluding. By agreeing to these Terms, you agree not to indulge in any unfair game practice that may provide undue advantage to you or any other User.</li>
                  <li>In the event any User is found undertaking such activity on the Platform, Company shall be entitled, at its sole and absolute discretion, to suspend or terminate such User’s account. The Company reserves the right to permanently block the account of the User involved in such activity. Any amounts deposited by such User on the Platform shall stand forfeited. The Company reserves the right to impose monetary penalties on Users found to be undertaking such practices on the Platform.</li>
                  <li>We reserve the right to withhold any necessary action, as it deems fit, against Users found indulging in unfair means. The action could include, inter alia, monetary penalties, temporary account suspension, redemption blocking, and/or permanent account deactivation. Any User involved in violation of these Terms is liable for prosecution.</li>
                  <li>Depositing and withdrawing without playing any or a reasonable amount of Game(s) is a violation of our fair play deposit and withdrawal policy. Consecutive deposits and withdrawals are considered money laundering actions, which is not permitted on the Platform. Any User found committing such an action is in violation of our fair play deposit and withdrawal policy and further investigation is subject to a penalty fee.</li>
                  <li>Any User deemed to be a fraud User for any reason, for example, found depositing or withdrawing from/to a fraudulent account, is subject to legal action from the Company’s management including but not limited to the confiscation of the User’s Account Balance and locking of the User’s Account.</li>
                  <li>Users caught dumping coins between accounts will be levied a minimum penalty of 40% of the coins dumped. The Company reserves the right to permanently block the account and forfeit the coins (including pending withdrawals) available in it if the User is found to be involved in any kind of malicious activity / unfair gameplay. If you suspect any User colluding in any game or involved in unfair practices, you can contact us via email at care@Sikandarji.in.</li>
                  <li>By using the Platform, including any sub-domains of the Platform, or related top-level domains including mobile sites, apps, APIs, and widgets, and/or registering yourself with us, you authorize us or our representatives to contact you via email or phone call or SMS including third-party messaging apps to offer you our services including but not limited to impart product knowledge, offer/explain any promotional offers running on the Platform and offers offered by third parties, for which reasons, personally identifiable information may be collected. Irrespective of the fact that you have registered yourself under DND or DNC or NCPR service, you still authorize us or our representatives to contact you by any means aforementioned for the above-mentioned purposes or any other related purpose till the time you are registered with us or even after cessation of registration.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Intellectual Property</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>The Platform includes a combination of Content created by the Company, its partners, affiliates, licensors, associates, and/or Users. The intellectual property rights (Intellectual Property Rights) in all software underlying Company and the Platform and material published on the Platform, including (but not limited to) Games, games software, advertisements, written Content, photographs, graphics, images, illustrations, marks, logos, audio or video clippings, and flash animation, is owned by Company, its affiliates, partners, licensors and/or associates. Users may not modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works of, distribute, publicly perform, publicly display, or in any way exploit any of the materials or Content on Company either in whole or in part without express written consent from Company. Nothing in these Terms shall be construed to convey and the Users by virtue of these Terms shall not acquire any ownership or other interest or right in any intellectual property of any of the materials or content on the Platform.</li>
                  <li>Users may request permission to use any Content by writing to the helpdesk at care@ludovijayta.com</li>
                  <li>Users are solely responsible for all materials (whether publicly posted or privately transmitted) that they upload, post, e-mail, transmit, or otherwise make available on the Platform (Users Content). Each User represents and warrants that he/she owns all Intellectual Property Rights in the User’s Content and that no part of the User’s Content infringes any third-party rights. Users further confirm and undertake to not display or use of the names, logos, marks, labels, trademarks, copyrights, or intellectual and proprietary rights of any third party on the Platform.</li>
                  <li>Users agree to indemnify and hold harmless the Company, its directors, officers, employees, affiliates, and assigns from and against all costs, damages, loss, and/ or harm including towards litigation costs and counsel fees, in respect of any third party claims that may be initiated including for infringement of Intellectual Property Rights arising out of such display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on Company, by such User or through the User’s commissions or omissions. We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you in which event you will assist and cooperate with the Company in asserting any available defenses.</li>
                  <li>Users hereby grant to the Company and its affiliates, partners, licensors, and associates a worldwide, irrevocable, perpetual, royalty-free, non-exclusive, sub-licensable, license to use, store, reproduce, create derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or publish Users’ Content for any of the following purposes:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>displaying Users’ Content on the Platform;</li>
                      <li>distributing Users’ Content, either electronically or via other media, to other Users seeking to download or otherwise acquire it; and/or</li>
                      <li>storing Users’ Content in a remote database accessible by end Users, for a charge.</li>
                    </ol>
                  </li>
                  <li>This license shall apply to the distribution and storage of Users’ Content in any form, medium, or technology.</li>
                  <li>The license shall not lapse due to non-use by the Company whether under any provision of the Copyright Act, 1957 or any other law.</li>
                  <li>All names, logos, marks, labels, trademarks, copyrights, or intellectual and proprietary rights on the Platform belonging to any person (including User), entity, or third party are recognized as proprietary to the respective owners and any claims, controversy or issues against these names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights must be directly addressed to the respective parties under notice to Company.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Testimonial Terms</h4>
                <ol className='pl-8 list-decimal space-y-4'>
                  <li>Company may capture and obtain visual and/or audio recordings or performances, still images of the User, and text provided by the User for the testimonial being provided towards the Platform (the results of which are the Recordings). The Recordings provided by the User are voluntary and Company is the sole and exclusive owner of all rights in and to the Recordings, and all elements thereof (including, without limitation, the copyright thereto). Without prejudice to the above, the User grants to the Company a perpetual royalty-free license, to publicly use, distribute, reproduce, create derivative works from, and perform/display the User’s name, voice, likeness, appearance, biographical information, and other indicia of its identity as included in the Recordings and any excerpts or version thereof for their marketing, in any language, and without any geographical limitation. Company may incorporate the recordings and any separate content (e.g., quotes, photos, videos, artwork, materials, etc.) to market their Platform and Services. The User also hereby waives any right to inspect or approve the finished matter based on the Recording that may be used now or in the future, whether that use is known to the user or unknown.</li>
                  <li>The Company is not obligated to use the Recordings if it so wishes. The User will not attempt to enjoin or otherwise impair the Company’s use of the Recordings that is in accordance with this Release.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Third-Party Sites, Services, and Products</h4>
                <ol className='pl-8 list-decimal space-y-4'>
                  <li>The Platform may contain links to other Internet sites owned and operated by third parties. Users’ use of each of those sites is subject to the conditions, if any, posted by such third-party sites. Company does not exercise control over any Internet sites apart from Company and cannot be held responsible for any content residing in any third-party Internet site. The Company’s inclusion of third-party Content or links to third-party Internet sites is not an endorsement by the Company of such third-party Internet sites.</li>
                  <li>User’s correspondence, transactions/offers, or related activities with third parties, including payment providers and verification service providers, are solely between the User and that third party. User’s correspondence, transactions, and usage of the services/offers of such third party shall be subject to the terms and conditions, policies, and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services/offers of such third party. User agrees that Company will not be responsible or liable for any loss or damage of any sort incurred as a result of any such transactions/offers with third parties. Any questions, complaints, or claims related to any third-party product or service should be directed to the appropriate vendor.</li>
                  <li>The Platform contains Content that is created by Company as well as content provided by third parties. Company does not warranty the accuracy, integrity, or quality of the content provided by third parties and such content may not be relied upon by the Users in utilizing the Services provided on the Platform including while participating in any of the Games hosted on the Platform.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Privacy</h4>
                <p>
                  By using the Platform and providing any of your personal information to the Platform, You affirmatively consent and agree to comply with our Privacy Policy (link given above), guidelines, and statements as may be applicable from time to time, which are incorporated into and forms an integral part of these Terms. If you do not agree to the terms of the Privacy Policy in its entirety or have objections to the use of your information, you may not access or otherwise use the Platform or its Services.
                </p>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Disconnection and Technical Issues</h4>
                <ol className='pl-8 list-decimal space-y-4'>
                  <li>You understand and acknowledge that once a game has commenced, not being able to play due to slow internet connections, faulty hardware, technical failure due to customer’s hardware, internet connection failure, low computer configuration, or for any other reason not attributable to us does not require us to issue a refund of the participation amount you may have paid for participation.</li>
                  <li>In case of any technical failures, server crashes, breakdowns, software defects, disruption, or malfunction of service at our end, as a policy, we will cancel the Game(s) and refund the participation amounts after proper verification and no service fee will be charged for such Games and you accept that we are not responsible to you in all such cases. For any game, we have the right to cancel and refund the participation amount. In no case, other than a server crash, we are accountable for any of the User’s disconnections from the server. We are also not liable for any prospective Winnings from any incomplete game.</li>
                  <li>We do not hold any liability for any disconnection, lag, freeze, or interference in the network on the User’s computer or any other external networks</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Enforceability</h4>
                <ol className='pl-8 list-decimal space-y-4'>
                  <li>By registering, you are considered to have accepted and understood all the Terms herein and the relevant Game-specific rules and regulations. We recommend that you keep a copy of all transactions, gaming rules, cancellations, and payment policies. Our failure or delay to act or exercise any right or remedy with respect to a breach of any of these Terms by you does not amount to surrendering or waiving our rights to act with respect to any prior, concurrent, subsequent, or similar breaches.</li>
                  <li>If any judicial or quasi-judicial body in India declares any of the provisions of these Terms to be unlawful, invalid, void, or unenforceable for any reason, the validity and enforceability of the remaining provisions will not be affected. Any such inappropriate term or condition will be replaced with another term or condition that is valid and enforceable and is in most nearly with effect to the original invalid term. In such event, the parties shall be obligated to construe and interpret the void, illegal, or unenforceable provision with a valid, legal, and enforceable provision in such a manner that corresponds as closely as possible to Company’s intent and objective in the void, illegal or unenforceable provisions.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Disclaimer of Warranties</h4>
                <p>Company disclaims any and all warranties, expressed or implied, in connection with the underlying software of the Platform, the Website, and the Game(s), all of which are provided to the User as is.</p>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>You agree that the use of the Services and the access to the Platform is at Your own risk. The Services including the Platform, the Content, the Games, and any other materials contained on or provided through the Platform are provided “AS IS” and, to the fullest extent permitted by law, are provided without warranties of any kind, either express or implied. Without limiting the foregoing, Company does not make any warranties of fitness for a particular purpose, title, merchantability, completeness, availability, security, compatibility, or non-infringement; or that the Services will be uninterrupted, free of viruses, malware, or other harmful components, accurate, error-free or reliable.</li>
                  <li>No person affiliated or claiming affiliation with the Platform has the authority to extend such warranties.</li>
                  <li>Without limiting the generality of the foregoing, to the maximum extent permitted by applicable law, we shall have no liability for any damages or injury caused, in whole or in part, by contingencies or issues beyond our reasonable control, including, but not limited to:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>the acts of third parties</li>
                      <li>errors in the Content or the Platform</li>
                      <li>network failures</li>
                      <li>internet failures</li>
                      <li>software and hardware failures</li>
                      <li>viruses and other system attacks</li>
                      <li>labor stoppages</li>
                      <li>Riots</li>
                      <li>acts of government or god</li>
                      <li>natural disasters</li>
                      <li>acts of terrorism</li>
                      <li>communication line failure, or </li>
                      <li>theft, destruction of, unauthorized access to, alteration of, or use of records.</li>
                    </ol>
                  </li>
                  <li>To the maximum extent permitted by applicable law, you hereby agree that you shall have no remedy in respect of any statement, representation, assurance, or warranty (whether made innocently or negligently) that is not set out in these Terms. You agree that you shall have no claim for innocent or negligent misrepresentation or negligent misstatement based on any statement in these Terms.</li>
                  <li>The foregoing limitations shall apply regardless of whether
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>liability or damage is alleged for breach of contract, tortious behavior, negligence, or under any other theory or cause of action, and/or</li>
                      <li>the party against which liability or damages is sought was advised of the possibility thereof. For the avoidance of doubt, nothing in these Terms shall limit or exclude liability for</li>
                    </ol>
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>death or personal injury caused by negligence; or</li>
                      <li>Fraud.</li>
                    </ol>
                  </li>
                  <li>To the maximum extent permitted by applicable law, you agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to these Terms, the Platform, or any part thereof, must be asserted within one (1) year after such claim or cause of action arose, or it shall be forever barred.</li>
                  <li>You agree and acknowledge that Company does not promise or ensure that you will be able to access your Account whenever you want. It is entirely possible that you may not be able to access your Account, or the Platform provided by the Company at times or for extended periods of time due to, but not limited to system maintenance and updates.</li>
                  <li>You agree and acknowledge that participation in the Games of Skill hosted by the Company may result in financial loss to you. With full knowledge of the facts and circumstances surrounding the Game(s) hosted on the Platform, you are voluntarily participating in the Game(s) and assume all responsibility for it and the risk resulting from your participation, including all risks of financial loss. The Company makes no guarantees, warranties, representations, or other promises relating to the game(s) and assumes no liability or responsibility for any financial loss that you may sustain as a result of participation in the Game(s).</li>
                  <li>You will be solely responsible for any delay and/or damage to your computer systems or loss of data that results from the installation of any software on your computer, and we expressly disclaim liability for any such failure and/or delay.</li>
                  <li>You agree to assume the entire risk as to the results and performance of any software and/or Game(s) availed by you on the Platform. As such, the result and performance among other things depend on your internet connection and hardware. You also assume the entire cost of all servicing, repair, and/or correction of your hardware when you access, download, or execute software or Game(s) available on the Platform. We explicitly disclaim liability for any delay or failure to perform resulting from the installation of any software on your computer.</li>
                  <li>You specifically acknowledge, agree, and accept that we are not liable to you for:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>the defamatory, offensive, or illegal conduct of any other User or for anything that turns out to be misleading, inaccurate, defamatory, threatening, obscene, or otherwise illegal whether originating from another User or otherwise;</li>
                      <li>any loss whatsoever arising from the use, abuse, or misuse of your Account on our Platform;</li>
                      <li>any loss incurred in transmitting information from you to our Platform by the Internet or by other connecting media;</li>
                      <li>any technical failures, system breakdowns, defects, delays, interruptions, manipulated or improper data transmission, loss or corruption of data or communications’ lines failure, distributed denial of service attacks, viruses, or any other adverse technological occurrences arising in connection with your access to or use of our Platform;</li>
                      <li>the accuracy, completeness, or currency of any information services provided or any statistics shown on the Platform.</li>
                    </ol>
                  </li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Indemnification and Limitation of Liability</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>You clearly understand and agree that Company shall under no circumstances (including, without limitation, in contract, negligence, or other tort), be liable for any direct, indirect, ancillary, special, incidental, consequential or exemplary, or punitive damages. This includes but is not limited to injury, claim, loss of data, loss of income, loss of profit or loss of opportunity, loss of or damage to property, damages for monetary loss, goodwill, use, data, or other intangible loss (even if Company has been advised of the possibility of such damages), resulting from or arising out of the use of or the inability to use the Platform, even if we have been advised or become aware of the possibility of such damages or loss or that such loss was foreseeable.</li>
                  <li>You agree to indemnify us and each of our respective general and limited partners, Users, shareholders, directors, officers, employees, agents, representatives, vendors, and business partners harmless from and against any and all claims, liabilities, obligations, losses, costs or debt, damages, and expenses (including attorneys’ fees and court costs) arising out of or relating to:
                    <ol className='list-decimal pl-8 space-y-3'>
                      <li>breach of these Terms, in tort (including negligence) third party claims or liabilities arising against the Company out of such a breach, based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these Terms;
                      </li>
                      <li>your use of the Platform in any matter that is contrary to applicable laws, with an intent to deceive, defraud cheat, mislead, or solicit any business, monetary or non-monetary consideration or information from another User;
                      </li>
                      <li>your breach of any applicable laws or governmental or judicial order which applies to your use of the Platform from a specific geography;
                      </li>
                      <li>your use of the Platform, including but not limited to your posting, use of, modification, or interaction with any content on the Platform;
                      </li>
                      <li>any unauthorized, improper, illegal, or wrongful use of your Account by any person, including a third party, whether or not authorized or permitted by you;
                      </li>
                      <li>your User Content</li>
                      <li>use by any other person accessing the Platform using your username or password, whether or not with your authorization,</li>
                      <li>the use by us of information provided by you through our Platform.</li>
                    </ol>
                  </li>
                  <li>from any income tax demand raised (including and not limited to tax, interest, penalty, withholding tax, or any other amount payable under the Indian Income-tax Act, 1961) arising on account of your misrepresentation and/ or your non-compliance with the terms and conditions mentioned therein. You agree that any income tax demand (including and not limited to tax, interest, penalty, withholding tax, or any other amount payable under the Indian Income-tax Act, 1961) which is paid/ payable by us in this regard, will be recovered by us and debited from your Play Money and Winnings.</li>
                  <li>This indemnification obligation will survive the expiry or termination of these Terms and your use of the Platform.
                  </li>
                  <li>There could be instances where the Company is not able to receive prompt updates about the change in applicable laws of your place of stay. It is your obligation to ensure that any activities you engage in on the Platform are legal as per the applicable laws. You agree to indemnify and hold harmless, the Company or its Platform, from any claim, demand, damage, or loss whatsoever coming out due to your non-compliance with the laws of your jurisdiction.
                  </li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Termination</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>We may change, suspend or discontinue any aspect of the Platform at any time, including the availability of any Platform’s feature, database, or Content. We may also impose limits on certain features and services or restrict your access to parts or the Platform, without notice or liability at any time in our exclusive discretion, without prejudice to any legal or equitable remedies available to us, for any reason or purpose. However, under normal circumstances, we will only do so where there has been conducted that we believe violates these Terms or other rules and regulations or guidelines posted on the Platform or conduct which we believe is harmful to other Users, to our businesses, or other information providers.</li>
                  <li>Upon any termination of these Terms, you shall immediately discontinue your use and access to the Platform and destroy all materials obtained from it. You hereby agree and consent to the above and agree and acknowledge that we can, at our sole discretion, exercise our right in relation to any or all of the above, and that we shall not be liable in any manner of the same; and you agree, acknowledge and consent to the same.</li>
                  <li>You acknowledge that your representations, undertakings, and warranties and the clauses relating to indemnities, limitation of liability, grant of a license, governing law and jurisdiction, and confidentiality shall survive the efflux of time and the termination of these Terms.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Publicity</h4>
                <p>
                  Acceptance of a prize by the Winner constitutes permission for the Company, and its affiliates to use the winner’s name, likeness, voice, and comments for advertising and promotional purposes in any media worldwide for purposes of advertising and trade without any further permissions or consent and/or additional compensation whatsoever. The winners further undertake that they will be available for promotional purposes as planned and desired by the Company without any charge. The exact dates remain the sole discretion of the Company. Promotional activities may include but not be limited to press events, internal meetings, and ceremonies/functions.
                </p>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">Dispute Resolution</h4>
                <ol className='list-decimal pl-8 space-y-4'>
                  <li>In case you have any grievances with respect to the Platform or the Services, you can send an email to the Grievance Redressal Officer  (hereinafter referred to as the Grievance Officer) at [support@ludovijayta.com]. We reserve the right to replace the Grievance Redressal Officer at any time without any notice or intimation to you. You can directly escalate any disputes to our management team by contacting the Grievance Redressal officer.</li>
                  <li>Subject to the clauses below, the courts of competent jurisdiction at Udaipur, Rajasthan shall have exclusive jurisdiction to determine any and all disputes arising out of, or in connection with the Platform provided by the Company (including the games, construction, validity, interpretation, and enforceability of these Terms, or the rights and obligations of the Users), as well as the exclusive jurisdiction to grant interim or preliminary relief in case of any dispute referred to arbitration as given below. All such issues and questions shall be governed and construed in accordance with the laws of India.</li>
                  <li>In the event of any legal dispute (which may be a legal issue or question) which may arise, the party raising the dispute shall provide a written notification (Notification) to the other party. On receipt of the Notification, the parties shall first try to resolve the dispute through discussions. In the event that the parties are unable to resolve the dispute within fifteen (15) days of receipt of the Notification, the dispute shall be settled by arbitration.</li>
                  <li>The seat and venue of arbitration shall be Jaipur, Rajasthan, India. All arbitration proceedings shall be conducted in English and in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as amended from time to time. The parties shall mutually appoint a sole arbitrator.</li>
                  <li>The arbitration award will be final and binding on the parties, and each party will bear its own costs of arbitration and equally share the fees of the arbitrator unless the arbitral tribunal decides otherwise.</li>
                  <li>Nothing contained in these Terms shall prevent the Company from seeking and obtaining interim or permanent equitable or injunctive relief, or any other relief available to safeguard its interest prior to, during, or following the filing of arbitration proceedings or pending the execution of a decision or award in connection with any arbitration proceedings from any courts of competent jurisdiction at Haryana to grant the same. The pursuit of equitable or injunctive relief shall not constitute a waiver on the part of the Company to pursue any remedy for monetary damages through the arbitration described herein.</li>
                </ol>
              </div>
              <div className='space-y-3'>
                <h4 className="font-bold">User Balances</h4>
                <p>Not with standing anything contained in these terms or any other policies, but subject to applicable law, Users agree and acknowledge that should the User Account remain inactive for a period of [12 (twelve)] months, the Company will transfer such amount to the User’s gameplay money balances to a reserve account maintained by Company (Reserve Account) from which the User may claim such gameplay money balances, subject to the User’s consent to additional KYC and user identification measures for claiming amounts from such Reserve Account. The Company will notify the User of the existence of such unused balance and the transfer thereof 45 (forty-five) days prior to the date of expiry of the Play Money amount by way of SMS, email, or call. The User agrees that if the User does not use the Services or utilize the gameplay money balances or request for a refund (where applicable), during such notice period then he/she consents to the transfer of the amount in the gameplay money balances, which shall be utilized by Company for spreading awareness on safety measures and best practices for online gaming.</p>
              </div>
            </div>
          </div>
        </div>

      </Container>
    </section>
  )
}

export default TermsAndConditions